AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 120

Style/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
